In [158]:
import pandas as pd

In [159]:
df_1 = pd.read_csv('/content/Patient_Data.csv')

In [160]:
df_1.head()

,PatientID,Name,Department,Doctor,BillAmount,ReceptionistID,CheckInTime
0,101,Alice,Cardiology,Dr. Smith,5000.0,1,2023-01-10 09:00
1,102,Bob,Neurology,Dr. John,NaN,2,2023-01-11 10:30
2,103,Charlie,Orthopedics,Dr. Lee,7500.0,1,2023-01-12 11:00
3,104,David,Cardiology,Dr. Smith,6200.0,3,2023-01-13 12:00
4,105,Eva,Dermatology,Dr. Rose,NaN,2,2023-01-14 08:45

In [161]:
df_1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   PatientID       6 non-null      int64
 1   Name            6 non-null      object
 2   Department      6 non-null      object
 3   Doctor          6 non-null      object
 4   BillAmount      4 non-null      float64
 5   ReceptionistID  6 non-null      int64
 6   CheckInTime     6 non-null      object
dtypes: float64(1), int64(2), object(4)
memory usage: 468.0+ bytes

In [162]:
df_1.isnull().sum()

PatientID         0
Name              0
Department        0
Doctor            0
BillAmount        2
ReceptionistID    0
CheckInTime       0
dtype: int64

iam trying to remove the null values by replacing them with the mean of the respective individual column

In [163]:
mean_bill = df_1['BillAmount'].mean()

In [164]:
df_1['BillAmount'] = df_1['BillAmount'].fillna(mean_bill)

In [165]:
df_1.isnull().sum()

PatientID         0
Name              0
Department        0
Doctor            0
BillAmount        0
ReceptionistID    0
CheckInTime       0
dtype: int64

In [166]:
df_1.head()

,PatientID,Name,Department,Doctor,BillAmount,ReceptionistID,CheckInTime
0,101,Alice,Cardiology,Dr. Smith,5000.0,1,2023-01-10 09:00
1,102,Bob,Neurology,Dr. John,5925.0,2,2023-01-11 10:30
2,103,Charlie,Orthopedics,Dr. Lee,7500.0,1,2023-01-12 11:00
3,104,David,Cardiology,Dr. Smith,6200.0,3,2023-01-13 12:00
4,105,Eva,Dermatology,Dr. Rose,5925.0,2,2023-01-14 08:45

dropping the columns which are not required in here the axis = 1 , means we are dropping the column

and the axis = 0 means we are dropping the rows

In [167]:
df_1 = df_1.drop(['ReceptionistID','CheckInTime'],axis=1)

In [168]:
df_1 = df_1.drop_duplicates(subset='PatientID')

In [169]:
df_1.groupby('Department')['BillAmount'].sum()

Department
Cardiology     11200.0
Dermatology     5925.0
Neurology       5925.0
Orthopedics     7500.0
Name: BillAmount, dtype: float64

we grouped the values based on the total revenue which is generated by the each department

In [170]:
#finding and dropping the duplicates
df_1.duplicated()

0    False
1    False
2    False
3    False
4    False
dtype: bool

In [171]:
df_1.duplicated().sum()

np.int64(0)

In [172]:
#Checking duplicates based on a specific column
df_1.duplicated(subset='PatientID')

0    False
1    False
2    False
3    False
4    False
dtype: bool

In [173]:
df_2 = pd.read_csv('/content/Billing_Data.csv')

In [174]:
df_2.head()

   PatientID  InsuranceCovered  FinalAmount
0        101              2000         3000
1        102              1500         3500
2        103              2500         5000
3        104              3000         3200
4        105              1000         4000

In [175]:
df_2.duplicated().sum()

np.int64(0)

In [176]:
df_2 = df_2.drop_duplicates(subset='PatientID')

In [177]:
merged_dataset =df_1.merge(
    df_2 ,
    on='PatientID'
)

In [178]:
merged_dataset.head()

,PatientID,Name,Department,Doctor,BillAmount,InsuranceCovered,FinalAmount
0,101,Alice,Cardiology,Dr. Smith,5000.0,2000,3000
1,102,Bob,Neurology,Dr. John,5925.0,1500,3500
2,103,Charlie,Orthopedics,Dr. Lee,7500.0,2500,5000
3,104,David,Cardiology,Dr. Smith,6200.0,3000,3200
4,105,Eva,Dermatology,Dr. Rose,5925.0,1000,4000

In [179]:
merged_dataset.isnull().sum()

PatientID           0
Name                0
Department          0
Doctor              0
BillAmount          0
InsuranceCovered    0
FinalAmount         0
dtype: int64

In [180]:
merged_dataset.groupby('Department')['BillAmount'].mean()

Department
Cardiology     5600.0
Dermatology    5925.0
Neurology      5925.0
Orthopedics    7500.0
Name: BillAmount, dtype: float64

In [184]:
import pandas as pd

new_patients = pd.DataFrame({
    'PatientID':[106,107],
    'Name':['Frank','Grace'],
    'Department':['Neurology','Cardiology'],
    'Doctor':['Dr. John','Dr. Smith'],
    'BillAmount':[4500,6800],
    'CheckInTime':['2023-01-15 10:00','2023-01-16 11:30'],
    'InsuranceCovered':[1500,2500],
    'FinalAmount':[3000,4300]
})

final_dataset = pd.concat([merged_dataset, new_patients], ignore_index=True)

print(final_dataset)

   PatientID     Name   Department     Doctor  BillAmount  InsuranceCovered  \
0        101    Alice   Cardiology  Dr. Smith      5000.0              2000
1        102      Bob    Neurology   Dr. John      5925.0              1500
2        103  Charlie  Orthopedics    Dr. Lee      7500.0              2500
3        104    David   Cardiology  Dr. Smith      6200.0              3000
4        105      Eva  Dermatology   Dr. Rose      5925.0              1000
5        106    Frank    Neurology   Dr. John      4500.0              1500
6        107    Grace   Cardiology  Dr. Smith      6800.0              2500

   FinalAmount       CheckInTime
0         3000               NaN
1         3500               NaN
2         5000               NaN
3         3200               NaN
4         4000               NaN
5         3000  2023-01-15 10:00
6         4300  2023-01-16 11:30

In [185]:
new_billing_columns = pd.DataFrame({
    'InsuranceType':['Gold','Silver','Gold','Silver','Gold'],
    'PaymentStatus':['Paid','Pending','Paid','Paid','Pending']
})

final_dataset = pd.concat(
    [merged_dataset, new_billing_columns],
    axis=1
)

print(final_dataset)

   PatientID     Name   Department     Doctor  BillAmount  InsuranceCovered  \
0        101    Alice   Cardiology  Dr. Smith      5000.0              2000
1        102      Bob    Neurology   Dr. John      5925.0              1500
2        103  Charlie  Orthopedics    Dr. Lee      7500.0              2500
3        104    David   Cardiology  Dr. Smith      6200.0              3000
4        105      Eva  Dermatology   Dr. Rose      5925.0              1000

   FinalAmount InsuranceType PaymentStatus
0         3000          Gold          Paid
1         3500        Silver       Pending
2         5000          Gold          Paid
3         3200        Silver          Paid
4         4000          Gold       Pending